#pragma once

namespace Ygg::Input
{
    enum EKeyCode;
    enum EMouseButton;

    bool IsKeyPressed(EKeyCode keyCode) noexcept;
    bool IsKeyReleased(EKeyCode keyCode) noexcept;
    bool IsKeyToggled(EKeyCode keyCode) noexcept;

    bool IsMouseButtonPressed(EMouseButton button) noexcept;
    bool IsMouseButtonReleased(EMouseButton button) noexcept;
    bool IsMouseButtonToggled(EMouseButton button) noexcept;

    enum EKeyCode
    {
        eKeyCode_YggKeyBackspace = 0x08,
        eKeyCode_YggKeyTab = 0x09,
        eKeyCode_YggKeyClear = 0x0C,
        eKeyCode_YggKeyReturn = 0x0D,
        eKeyCode_YggKeyShift = 0x10,
        eKeyCode_YggKeyControl = 0x11,
        eKeyCode_YggKeyMenu = 0x12,
        eKeyCode_YggKeyPause = 0x13,
        eKeyCode_YggKeyCaps = 0x14,
        eKeyCode_YggKeyEscape = 0x1B,
        eKeyCode_YggKeySpace = 0x20,
        eKeyCode_YggKeyPgUp = 0x21,
        eKeyCode_YggKeyPgDown = 0x22,
        eKeyCode_YggKeyEnd = 0x23,
        eKeyCode_YggKeyHome = 0x24,
        eKeyCode_YggKeyLeftArrow = 0x25,
        eKeyCode_YggKeyUpArrow = 0x26,
        eKeyCode_YggKeyRightArrow = 0x27,
        eKeyCode_YggKeyDownArrow = 0x28,
        eKeyCode_YggKeySelect = 0x29,
        eKeyCode_YggKeyPrint = 0x2A,
        eKeyCode_YggKeyExecute = 0x2B,
        eKeyCode_YggKeySnapshot = 0x2C,
        eKeyCode_YggKeyInsert = 0x2D,
        eKeyCode_YggKeyDelete = 0x2E,
        eKeyCode_YggKeyHelp = 0x2F,
        eKeyCode_YggKey0 = 0x30,
        eKeyCode_YggKey1 = 0x31,
        eKeyCode_YggKey2 = 0x32,
        eKeyCode_YggKey3 = 0x33,
        eKeyCode_YggKey4 = 0x34,
        eKeyCode_YggKey5 = 0x35,
        eKeyCode_YggKey6 = 0x36,
        eKeyCode_YggKey7 = 0x37,
        eKeyCode_YggKey8 = 0x38,
        eKeyCode_YggKey9 = 0x39,
        eKeyCode_YggKeyA = 0x41,
        eKeyCode_YggKeyB = 0x42,
        eKeyCode_YggKeyC = 0x43,
        eKeyCode_YggKeyD = 0x44,
        eKeyCode_YggKeyE = 0x45,
        eKeyCode_YggKeyF = 0x46,
        eKeyCode_YggKeyG = 0x47,
        eKeyCode_YggKeyH = 0x48,
        eKeyCode_YggKeyI = 0x49,
        eKeyCode_YggKeyJ = 0x4A,
        eKeyCode_YggKeyK = 0x4B,
        eKeyCode_YggKeyL = 0x4C,
        eKeyCode_YggKeyM = 0x4D,
        eKeyCode_YggKeyN = 0x4E,
        eKeyCode_YggKeyO = 0x4F,
        eKeyCode_YggKeyP = 0x50,
        eKeyCode_YggKeyQ = 0x51,
        eKeyCode_YggKeyR = 0x52,
        eKeyCode_YggKeyS = 0x53,
        eKeyCode_YggKeyT = 0x54,
        eKeyCode_YggKeyU = 0x55,
        eKeyCode_YggKeyV = 0x56,
        eKeyCode_YggKeyW = 0x57,
        eKeyCode_YggKeyX = 0x58,
        eKeyCode_YggKeyY = 0x59,
        eKeyCode_YggKeyZ = 0x5A,
        eKeyCode_YggKeyLeftWin = 0x5B,
        eKeyCode_YggKeyRightWin = 0x5C,
        eKeyCode_YggKeyApps = 0x5D,
        eKeyCode_YggKeySleep = 0x5F,
        eKeyCode_YggKeyNum0 = 0x60,
        eKeyCode_YggKeyNum1 = 0x61,
        eKeyCode_YggKeyNum2 = 0x62,
        eKeyCode_YggKeyNum3 = 0x63,
        eKeyCode_YggKeyNum4 = 0x64,
        eKeyCode_YggKeyNum5 = 0x65,
        eKeyCode_YggKeyNum6 = 0x66,
        eKeyCode_YggKeyNum7 = 0x67,
        eKeyCode_YggKeyNum8 = 0x68,
        eKeyCode_YggKeyNum9 = 0x69,
        eKeyCode_YggKeyMultiply = 0x6A,
        eKeyCode_YggKeyAdd = 0x6B,
        eKeyCode_YggKeySeperator = 0x6C,
        eKeyCode_YggKeySubtract = 0x6D,
        eKeyCode_YggKeyDecimal = 0x6E,
        eKeyCode_YggKeyDivide = 0x6F,
        eKeyCode_YggKeyF1 = 0x70,
        eKeyCode_YggKeyF2 = 0x71,
        eKeyCode_YggKeyF3 = 0x72,
        eKeyCode_YggKeyF4 = 0x73,
        eKeyCode_YggKeyF5 = 0x74,
        eKeyCode_YggKeyF6 = 0x75,
        eKeyCode_YggKeyF7 = 0x76,
        eKeyCode_YggKeyF8 = 0x77,
        eKeyCode_YggKeyF9 = 0x78,
        eKeyCode_YggKeyF10 = 0x79,
        eKeyCode_YggKeyF11 = 0x7A,
        eKeyCode_YggKeyF12 = 0x7B,
        eKeyCode_YggKeyF13 = 0x7C,
        eKeyCode_YggKeyF14 = 0x7D,
        eKeyCode_YggKeyF15 = 0x7E,
        eKeyCode_YggKeyF16 = 0x7F,
        eKeyCode_YggKeyF17 = 0x80,
        eKeyCode_YggKeyF18 = 0x81,
        eKeyCode_YggKeyF19 = 0x82,
        eKeyCode_YggKeyF20 = 0x83,
        eKeyCode_YggKeyF21 = 0x84,
        eKeyCode_YggKeyF22 = 0x85,
        eKeyCode_YggKeyF23 = 0x86,
        eKeyCode_YggKeyF24 = 0x87,
        eKeyCode_YggKeyNumlock = 0x90,
        eKeyCode_YggKeyScroll = 0x91,
        eKeyCode_YggKeyLeftShift = 0xA0,
        eKeyCode_YggKeyRightShift = 0xA1,
        eKeyCode_YggKeyLeftControl = 0xA2,
        eKeyCode_YggKeyRightControl = 0xA3,
        eKeyCode_YggKeyLeftMenu = 0xA4,
        eKeyCode_YggKeyRightMenu = 0xA5,
        eKeyCode_YggKeyOemPlus = 0xBB,
        eKeyCode_YggKeyOemComma = 0xBC,
        eKeyCode_YggKeyOemMinus = 0xBD,
        eKeyCode_YggKeyOemPeriod = 0xBE,
    };

    enum EMouseButton
    {
        eMouseButton_YggMouseButtonLEFT   = 0x01,
        eMouseButton_YggMouseButtonRIGHT  = 0x02,
        eMouseButton_YggMouseButtonMIDDLE = 0x04,
        eMouseButton_YggMouseButtonX1     = 0x05,
        eMouseButton_YggMouseButtonX2     = 0x06
    };
}
