#pragma once

namespace Ygg
{
    enum KeyCode;
    enum MouseButton;

    bool IsKeyPressed(KeyCode keyCode) noexcept;
    bool IsKeyReleased(KeyCode keyCode) noexcept;
    bool IsKeyToggled(KeyCode keyCode) noexcept;

    bool IsMouseButtonPressed(MouseButton button) noexcept;
    bool IsMouseButtonReleased(MouseButton button) noexcept;
    bool IsMouseButtonToggled(MouseButton button) noexcept;

    enum KeyCode
    {
        YGG_KEY_BACKSPACE = 0x08,
        YGG_KEY_TAB = 0x09,
        YGG_KEY_CLEAR = 0x0C,
        YGG_KEY_RETURN = 0x0D,
        YGG_KEY_SHIFT = 0x10,
        YGG_KEY_CONTROL = 0x11,
        YGG_KEY_MENU = 0x12,
        YGG_KEY_PAUSE = 0x13,
        YGG_KEY_CAPS = 0x14,
        YGG_KEY_ESCAPE = 0x1B,
        YGG_KEY_SPACE = 0x20,
        YGG_KEY_PG_UP = 0x21,
        YGG_KEY_PG_DOWN = 0x22,
        YGG_KEY_END = 0x23,
        YGG_KEY_HOME = 0x24,
        YGG_KEY_LEFT_ARROW = 0x25,
        YGG_KEY_UP_ARROW = 0x26,
        YGG_KEY_RIGHT_ARROW = 0x27,
        YGG_KEY_DOWN_ARROW = 0x28,
        YGG_KEY_SELECT = 0x29,
        YGG_KEY_PRINT = 0x2A,
        YGG_KEY_EXECUTE = 0x2B,
        YGG_KEY_SNAPSHOT = 0x2C,
        YGG_KEY_INSERT = 0x2D,
        YGG_KEY_DELETE = 0x2E,
        YGG_KEY_HELP = 0x2F,
        YGG_KEY_0 = 0x30,
        YGG_KEY_1 = 0x31,
        YGG_KEY_2 = 0x32,
        YGG_KEY_3 = 0x33,
        YGG_KEY_4 = 0x34,
        YGG_KEY_5 = 0x35,
        YGG_KEY_6 = 0x36,
        YGG_KEY_7 = 0x37,
        YGG_KEY_8 = 0x38,
        YGG_KEY_9 = 0x39,
        YGG_KEY_A = 0x41,
        YGG_KEY_B = 0x42,
        YGG_KEY_C = 0x43,
        YGG_KEY_D = 0x44,
        YGG_KEY_E = 0x45,
        YGG_KEY_F = 0x46,
        YGG_KEY_G = 0x47,
        YGG_KEY_H = 0x48,
        YGG_KEY_I = 0x49,
        YGG_KEY_J = 0x4A,
        YGG_KEY_K = 0x4B,
        YGG_KEY_L = 0x4C,
        YGG_KEY_M = 0x4D,
        YGG_KEY_N = 0x4E,
        YGG_KEY_O = 0x4F,
        YGG_KEY_P = 0x50,
        YGG_KEY_Q = 0x51,
        YGG_KEY_R = 0x52,
        YGG_KEY_S = 0x53,
        YGG_KEY_T = 0x54,
        YGG_KEY_U = 0x55,
        YGG_KEY_V = 0x56,
        YGG_KEY_W = 0x57,
        YGG_KEY_X = 0x58,
        YGG_KEY_Y = 0x59,
        YGG_KEY_Z = 0x5A,
        YGG_KEY_LEFT_WIN = 0x5B,
        YGG_KEY_RIGHT_WIN = 0x5C,
        YGG_KEY_APPS = 0x5D,
        YGG_KEY_SLEEP = 0x5F,
        YGG_KEY_NUM_0 = 0x60,
        YGG_KEY_NUM_1 = 0x61,
        YGG_KEY_NUM_2 = 0x62,
        YGG_KEY_NUM_3 = 0x63,
        YGG_KEY_NUM_4 = 0x64,
        YGG_KEY_NUM_5 = 0x65,
        YGG_KEY_NUM_6 = 0x66,
        YGG_KEY_NUM_7 = 0x67,
        YGG_KEY_NUM_8 = 0x68,
        YGG_KEY_NUM_9 = 0x69,
        YGG_KEY_MULTIPLY = 0x6A,
        YGG_KEY_ADD = 0x6B,
        YGG_KEY_SEPERATOR = 0x6C,
        YGG_KEY_SUBTRACT = 0x6D,
        YGG_KEY_DECIMAL = 0x6E,
        YGG_KEY_DIVIDE = 0x6F,
        YGG_KEY_F1 = 0x70,
        YGG_KEY_F2 = 0x71,
        YGG_KEY_F3 = 0x72,
        YGG_KEY_F4 = 0x73,
        YGG_KEY_F5 = 0x74,
        YGG_KEY_F6 = 0x75,
        YGG_KEY_F7 = 0x76,
        YGG_KEY_F8 = 0x77,
        YGG_KEY_F9 = 0x78,
        YGG_KEY_F10 = 0x79,
        YGG_KEY_F11 = 0x7A,
        YGG_KEY_F12 = 0x7B,
        YGG_KEY_F13 = 0x7C,
        YGG_KEY_F14 = 0x7D,
        YGG_KEY_F15 = 0x7E,
        YGG_KEY_F16 = 0x7F,
        YGG_KEY_F17 = 0x80,
        YGG_KEY_F18 = 0x81,
        YGG_KEY_F19 = 0x82,
        YGG_KEY_F20 = 0x83,
        YGG_KEY_F21 = 0x84,
        YGG_KEY_F22 = 0x85,
        YGG_KEY_F23 = 0x86,
        YGG_KEY_F24 = 0x87,
        YGG_KEY_NUMLOCK = 0x90,
        YGG_KEY_SCROLL = 0x91,
        YGG_KEY_LEFT_SHIFT = 0xA0,
        YGG_KEY_RIGHT_SHIFT = 0xA1,
        YGG_KEY_LEFT_CONTROL = 0xA2,
        YGG_KEY_RIGHT_CONTROL = 0xA3,
        YGG_KEY_LEFT_MENU = 0xA4,
        YGG_KEY_RIGHT_MANU = 0xA5,
        YGG_KEY_OEM_PLUS = 0xBB,
        YGG_KEY_OEM_COMMA = 0xBC,
        YGG_KEY_OEM_MINUS = 0xBD,
        YGG_KEY_OEM_PERIOD = 0xBE,
    };

    enum MouseButton
    {
        YGG_MOUSE_BUTTON_LEFT   = 0x01,
        YGG_MOUSE_BUTTON_RIGHT  = 0x02,
        YGG_MOUSE_BUTTON_MIDDLE = 0x04,
        YGG_MOUSE_BUTTON_X1     = 0x05,
        YGG_MOUSE_BUTTON_X2     = 0x06
    };
}
